-- 코드를 작성해주세요
-- 더 이상 업그레이드 할 수 없는 아이템 = 리프노드 아이템
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
LEFT JOIN ITEM_TREE AS T
  ON T.PARENT_ITEM_ID = I.ITEM_ID 
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;