SELECT
  CC.CAR_ID AS CAR_ID,
  CC.CAR_TYPE AS CAR_TYPE, 
  ROUND(CC.DAILY_FEE * 30 * (100 - DP.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
  ON CC.CAR_ID = RH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
  ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE CC.CAR_TYPE IN ('세단', 'SUV') 
  AND CC.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-12-01' AND END_DATE >= '2022-11-01'
      )
  AND DP.DURATION_TYPE = '30일 이상'
GROUP BY CC.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
 
  