WITH pr AS (
  SELECT
    ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS prk
  FROM ECOLI_DATA
)
SELECT
  ID,
  CASE
    WHEN prk <= 0.25 THEN 'CRITICAL'
    WHEN prk <= 0.50 THEN 'HIGH'
    WHEN prk <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS COLONY_NAME
FROM pr
ORDER BY ID ASC;