/*
 조건
    1. 2021년 가입
    2. 상품을 구매한 회원 수와 

*/

SELECT
  YEAR(SALE.SALES_DATE) AS YEAR,
  MONTH(SALE.SALES_DATE) AS MONTH,
  COUNT(DISTINCT INFO.USER_ID) AS PURCHASED_USERS,
  ROUND(COUNT(DISTINCT INFO.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
FROM USER_INFO AS INFO
JOIN ONLINE_SALE AS SALE
  ON INFO.USER_ID = SALE.USER_ID
WHERE YEAR(INFO.JOINED) = 2021      # 2021년 가입 
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC



