/*

 조건
    1. 생산일자 2022-05
    2. 총매출 계산, 총매출 기준 내림차순 정렬, 같으면 ID 기준 오름차순 정렬
    
*/

SELECT
  FP.PRODUCT_ID,
  FP.PRODUCT_NAME,
  SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN FOOD_ORDER AS FO
  ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC