-- 코드를 입력하세요

WITH cte AS(
    SELECT 
      *,
      CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'   
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        ELSE NULL
      END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT 
  HISTORY_ID,
  ROUND(CC.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) *  
        (100 - IF(DP.DISCOUNT_RATE IS NULL, 0, DP.DISCOUNT_RATE)) * 0.01)  AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CC
JOIN cte
  ON CC.CAR_ID = cte.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
  ON CC.CAR_TYPE = DP.CAR_TYPE
  AND cte.DURATION_TYPE = DP.DURATION_TYPE
WHERE CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;