/*
 로직
    1. 리뷰를 가장 많이 작성한 회원 찾기
    2. 그 회원의 리뷰들 조회
        - 회원 이름, 리뷰 텍스트, 리뷰 작성일 출력 (작성일 DATE_FORMAT)
    3. 정렬 - 작성일 ASC, 텍스트 ASC
*/

SELECT
  MP.MEMBER_NAME AS MEMBER_NAME,
  RR.REVIEW_TEXT AS REVIEW_TEXT,
  DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR
  ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID 
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC


