-- 코드를 작성해주세요
SELECT Child.ID, Child.GENOTYPE, Parent.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA Child, ECOLI_DATA Parent
WHERE Child.PARENT_ID = Parent.ID
AND Parent.GENOTYPE & Child.GENOTYPE = Parent.GENOTYPE
ORDER BY Child.ID ASC;